2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_setup.py:_flush():68] Configure stats pid to 867340
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_setup.py:_flush():68] Loading settings from /home/picarib/.config/wandb/settings
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_setup.py:_flush():68] Loading settings from /home/picarib/Projects/TangleNAS/wandb/settings
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_setup.py:_flush():68] Loading settings from environment variables
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_init.py:_log_setup():528] Logging user logs to /home/picarib/Projects/TangleNAS/wandb/run-20241229_144921-mlwnsszr/logs/debug.log
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_init.py:_log_setup():529] Logging internal logs to /home/picarib/Projects/TangleNAS/wandb/run-20241229_144921-mlwnsszr/logs/debug-internal.log
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_init.py:init():644] calling init triggers
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {'config_string': 'nl7_ed576_nh12121212121212_mr4444444', 'k': 'mlp_ratio', 'k_': 'mr', 'v_': '4444444', 'n_layer': 7, 'n_embd': 576, 'timestr': '20241229-144919', 'out_dir': 'output_tinystories/out_train_None_None_nl7_ed576_nh12121212121212_mr4444444_maxiter12000_9001_20241229-144919', 'eval_interval': 100, 'log_interval': 10, 'eval_iters': 100, 'eval_only': False, 'always_save_checkpoint': False, 'init_from': 'scratch', 'wandb_log': True, 'wandb_project': 'tinystories-gpt2enc', 'wandb_run_name': 'gpt2', 'gradient_accumulation_steps': 20, 'batch_size': 12, 'block_size': 224, 'dropout': 0.2, 'bias': False, 'learning_rate': 0.0005, 'max_iters': 12000, 'weight_decay': 0.1, 'beta1': 0.9, 'beta2': 0.99, 'grad_clip': 1.0, 'decay_lr': True, 'warmup_iters': 100, 'min_lr': 5e-05, 'backend': 'nccl', 'device': 'cuda', 'dtype': 'float16', 'compile': False}
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_init.py:init():680] starting backend
2024-12-29 14:49:21,570 INFO    MainThread:867340 [wandb_init.py:init():684] sending inform_init request
2024-12-29 14:49:21,573 INFO    MainThread:867340 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-12-29 14:49:21,574 INFO    MainThread:867340 [wandb_init.py:init():697] backend started and connected
2024-12-29 14:49:21,574 INFO    MainThread:867340 [wandb_init.py:init():790] updated telemetry
2024-12-29 14:49:21,576 INFO    MainThread:867340 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2024-12-29 14:49:21,933 ERROR   MainThread:867340 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your-team not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-29 14:49:21,933 ERROR   MainThread:867340 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "/home/picarib/anaconda3/envs/nas_dev/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1298, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/picarib/anaconda3/envs/nas_dev/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 404 Not Found: {"errors":[{"message":"entity your-team not found during upsertBucket","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-12-29 14:49:21,943 WARNING MsgRouterThr:867340 [router.py:message_loop():75] message_loop has been closed
